# Generated by Django 4.2.21 on 2025-06-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('r', 'raina'), ('d', 'dhoni'), ('v', 'virat')], default='r', max_length=50, verbose_name='Cricketer_name')),
                ('scores', models.IntegerField()),
            ],
        ),
    ]
