# Generated by Django 4.2.21 on 2025-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='name',
            field=models.CharField(choices=[('r', 'raina'), ('d', 'dhoni'), ('v', 'virat')], default='d', max_length=50, verbose_name='Cricketer_name'),
        ),
    ]
